config/routes.rb
CronDemo::Application.routes.draw do
  resources :jobs

  root "jobs#index"
  get "/history" => "jobs#history"
  post "jobs/new"
  post "/restart" => "jobs#restart"
  get "/restart" => "jobs#restart"
  get "/inactive" => "jobs#inactive"
  post "/jobs/clear_history" => "jobs#clear_history"

end

app/models/job.rb
class Job < ActiveRecord::Base
	validates :title, presence: true, uniqueness: true
	validates :command, presence: true
	validates :cron_input, presence: true
end

app/models/job_history.rb
class JobHistory < ActiveRecord::Base
end

app/models/job_scheduler.rb
class JobScheduler
	@@rscheduler = Rufus::Scheduler.new
	def check_cron_input
		# find some regex maybe to check if cron input is valid
	end

	# This runs BEFORE initializing a new Job. Jobs should only be
	# added to the database if this is successful
	# link the job to the rufus_id using the return
	def self.schedule(job)
		begin # the controller will delete the object if this returns nil
			cron_id = @@rscheduler.cron job.cron_input, times: job.times_to_run do
				begin # the only reason this should be false is an error, right?
					# Run the command, but puts for now
					puts job.command
					job.update(next_time: find_next(cron_id))

					if !job.times_to_run.nil? # update the remaining number of runs for those that are finite runs
						job.update(times_to_run: job.times_to_run - 1)
						if job.times_to_run <= 0
							job.update(active: false)
						end
					end
					JobHistory.create(success: true, job_id: job.id)
				rescue
					JobHistory.create(success: false, job_id: job.id)
				end
			end
			job.update(next_time: find_next(cron_id))
			return cron_id
		rescue
			return nil
		end
		#rescue false # in case of bad cron inputs
	end

	# unschedule the job associated with this database entry
	# make sure to call this before destroy!
	def self.unschedule(job)
		job.update(active: false)
		cron_job = @@rscheduler.job(job.rufus_id)
		if !cron_job.nil?
			@@rscheduler.unschedule(job.rufus_id)
			cron_job.kill
		else
			puts "Could not find cron job"
		end
	end

	def self.find_next(job_id)
		return @@rscheduler.job(job_id).next_time
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all(:conditions => {:active => true})
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end


  def inactive
    @jobs = Job.all(:conditions => {:active => false})
  end

  # restart an inactive job
  def restart
    @job = Job.find(params[:job])
    if !(rufus_id = JobScheduler.schedule(@job)).nil?
      @job.update(active: true)
      @job.update(rufus_id: rufus_id)
      redirect_to "/inactive"
    else
      redirect_to "/inactive"
    end
  end


  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        if !(rufus_id = JobScheduler.schedule(@job)).nil? 
          @job.update(rufus_id: rufus_id)
          @job.update(active: true)
          format.html { redirect_to "/jobs", notice: 'Job was successfully scheduled.' }
          format.json { render action: 'index', status: :created, location: @job }
        else
          @job.destroy
          format.html { render action: 'new' }
          format.json { render json: @job.errors, status: :unprocessable_entity }
        end
      else

        format.html { render action: 'new' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    JobScheduler.unschedule(@job)
    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  def history
    @history = JobHistory.all
  end

  def clear_history
    JobHistory.delete_all
    redirect_to "/history"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :command, :cron_input, :times_to_run)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
<% if @job.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

  <ul>
    <% @job.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :command %><br>
    <%= f.text_field :command, class: "form-control"  %>
  </div>
  <div class="field">
    <%= f.label :cron_input %><br>
    <%= f.text_field :cron_input, class: "form-control"  %>
  </div>
   <div class="field">
    <%= f.label :times_to_run %><br>
    <%= f.text_field :times_to_run, class: "form-control"  %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/jobs/history.html.erb
<div class = "row">
<div class = "col-sm-6">
<h1>History</h1>
</div>
<div class = "col-sm-6">

<%= button_to "Clear", {action: "clear_history", controller: "jobs" }, class: "btn btn-lg btn-default pull-right", confirm: "Are you sure you want to clear the history?" %>
</div>
</div>
<table class = "table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Command</th>
      <th>Cron input</th>
      <th>Success</th>
      <th>Time Run</th>
    </tr>
  </thead>

  <tbody>
    <% @history.reverse.each do |past_job| %>
      <% job = Job.find(past_job.job_id) %>
    <tr>
      <td><%= job.title %></td>
      <td><%= job.command %></td>
      <td><%= job.cron_input %></td>
      <td><%= past_job.success %></td>
      <td><%= past_job.created_at %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/jobs/inactive.html.erb
<h1>Inactive Jobs</h1>

<table class= "table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Command</th>
      <th>Times to Run</th>
      <th>Cron Input</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
    <tr>
      <td><%= job.title %></td>
      <td><%= job.command %></td>
      <td><%= job.times_to_run %></td>
      <td><%= job.cron_input %></td>
      <td><%= button_to 'Restart', {controller: "jobs", action: "restart", job: job}, class: "btn btn-sm btn-default"%></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/jobs/index.html.erb
<h1>Active Jobs</h1>

<table class= "table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Command</th>
      <th>Next Run</th>
      <th>Times to Run</th>
      <th>Cron Input</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
    <tr>
      <td><%= job.title %></td>
      <td><%= job.command %></td>
      <td><%= job.next_time %></td>
      <td><%= job.times_to_run || "(unlimited)" %></td>
      <td><%= job.cron_input %></td>
      <td><%= button_to 'Cancel', job, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-sm btn-default"%></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Job', new_job_path , class: "btn btn-primary btn-lg" %>

app/views/jobs/new.html.erb
<div class = "row">
	<div class = "col-sm-1">
	<%= link_to '< Back', jobs_path, class: "btn btn-xs btn-default" %>
	</div>
</div>
<div class = "row">
	<div class = "col-sm-6">

	<h1>Schedule a Job</h1>
	</div>
</div>
<div class = "row">
	<div class = "col-sm-6">
		<%= render 'form' %>
	</div>
</div>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Command name:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Command name:</strong>
  <%= @job.command %>
</p>

<p>
  <strong>Cron input:</strong>
  <%= @job.cron_input %>
</p>

<%= link_to '< Back', jobs_path, class: "btn btn-xs btn-default" %>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Cron Demo</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Active Jobs", "/jobs" %>
        </li>
        <li>
          <%= link_to "Inactive Jobs", "/inactive" %>
        </li>
        <li>
        <%= link_to "History", "/history" %>
        </li>
        
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>CronDemo</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<% if flash[:error] %>
	<div class="flash error"><%= flash[:error] %></div>
	<% end %>
	<% if flash[:success] %>
	<div class="flash success"><%= flash[:sucess] %></div>
	<% end %>
	<%= render "layouts/nav_bar" %>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>